services:
    engram:
        image: ghcr.io/ilyayturki/workspace:latest
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - HOST=0.0.0.0
            - PORT=3000
            - NUXT_RAWG_API=your-key-here
        volumes:
            - <path-to-library>:/app/library
            - <path-to-metadata>:/app/metadata
